import { StyleSheet } from 'react-native';
export default StyleSheet.create({
   container: {
      flex: 1,
      backgroundColor: '#fff',
      marginBottom: 16,
   },
   headerViewStyle: {
      marginVertical: 15,
      alignItems: 'center',
      justifyContent: 'center',
   },
   headerTextStyle: {
      fontSize: 24,
      fontWeight: '800',
   },
   cardViewStyle: {
      // top: '2.5%',
      width: '86%',
      // height: '80%',
      borderWidth: 0.5,
      borderRadius: 9.5,
      alignSelf: 'center',
      // alignItems: 'center',
      backgroundColor: '#fff',
      borderColor: '#ccc',
      // shadowOpacity: 0.75,
      // shadowRadius: 9.5,
      // shadowColor: 'grey',
      // shadowOffset: { height: 0, width: 0 },
   },
   cardHearderStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      marginVertical: 20,
   },
   cardHeaderTextStyle: {
      fontSize: 16,
      fontWeight: '700',
   },
   thumbViewStyle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
   },
   thumbsButtonStyle: {
      width: 90,
      height: 32,
      borderRadius: 15,
      alignItems: 'center',
      flexDirection: 'row',
      marginHorizontal: 7.5,
      justifyContent: 'center',
   },
   countTextStyle: {
      fontSize: 14,
      color: '#fff',
      paddingLeft: 7.5,
      fontWeight: '600',
   },
   epicVoteViewStyle: {
      alignItems: 'center',
      marginVertical: 12.5,
      justifyContent: 'center',
   },
   epicVoteTextStyle: {
      fontSize: 12,
      color: '#333',
      textAlign: 'center',
   },
   seprateStyle: {
      // height: 0.4,
      width: '90%',
      marginTop: 15,
      alignSelf: 'center',
      backgroundColor: 'gray',
   },
   renderItemViewStyle: {
      height: 35,
      width: '90%',
      borderRadius: 15,
      marginVertical: 3.5,
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fafafa',
   },
   itemProfileViewStyle: {
      height: 35,
      width: 35,
      borderRadius: 17.5,
   },
   nameTextStyle: {
      paddingLeft: 12.5,
      width: '75%',
      fontSize: 14,
   },
   itemThumbViewStyle: {
      height: 27,
      width: 27,
      borderRadius: 15,
      justifyContent: 'center',
      alignItems: 'center',
   },
});
