import { Assets } from "react-native-ui-lib";

Assets.loadAssetsGroup("challenges", {

  // fitnessChallenge: require("images/fitnessChallenge.png")
});

Assets.loadAssetsGroup("achievements", {

    ADDED_CITY: require("images/ADDED_CITY.png"),
    JOINED_FIRST_CHALLENGE: require("images/JOINED_FIRST_CHALLENGE.png"),

  SMASH_FIRST_ACTIVITY: require("images/SMASH_FIRST_ACTIVITY.png"),
    THREE_CHALLENGES: require("images/THREE_CHALLENGES.png"),
    REACHED_1K: require("images/REACHED_1K.png"),
    REACHED_10K: require("images/REACHED_10K.png"),
    REACHED_100K: require("images/REACHED_100K.png"),
  TEN_DAY_STREAK: require("images/TEN_DAY_STREAK.png"),
  SEVEN_DAY_STREAK: require("images/SEVEN_DAY_STREAK.png"),
    ADDED_REVIEW: require("images/ADDED_REVIEW.png"),
    THREE_DAY_STREAK: require("images/THREE_DAY_STREAK.png"),
    CREATE_A_TEAM: require("images/CREATE_A_TEAM.png"),
    WON_TEAM_TARGET: require("images/WON_TEAM_TARGET.png"),
    FOLLOWED_A_PLAYER: require("images/FOLLOWED_A_PLAYER.png"),

  })
Assets.loadAssetsGroup("bg", {

  // fitness: require("images/fitness.png"),
  // lifestyle: require("images/lifestyle.png"),
  // popular: require("images/popular.png"),
  shareBg: require('images/shareBg.png'),
  whitebadge: require('images/whitebadge.png'),
});
Assets.loadAssetsGroup('icons', {
  0: require('images/3.png'),
  1: require('images/7.png'),
  2: require('images/10.png'),
  3: require('images/14.png'),
  4: require('images/21.png'),
  5: require('images/30.png'),
  6: require('images/14.png'),
  7: require('images/14.png'),
  8: require('images/14.png'),
  9: require('images/14.png'),
  10: require('images/14.png'),
   bg: require('images/bg.png'),
   btn_back_day: require('images/btn_back_day.png'),
   vaccum: require('images/vaccuum.png'),
   meditation: require('images/meditation.png'),
   focus: require('images/focus.png'),
   water: require('images/water.png'),
   distance: require('images/distance.png'),
   bodyweight: require('images/bodyweight.png'),
   gratitude: require('images/gratitude.png'),
   pushups: require('images/pushups.png'),
   fire: require('images/fire.png'),
   training: require('images/training.png'),
   squats: require('images/squats.png'),
   smashappicon: require('images/smashappicon.png'),
   threeDays: require('images/3.png'),
  sevenDays: require('images/7.png'),
  tenDays: require('images/10.png'),
  fourteenDays: require('images/14.png'),
  twentyOneDays: require('images/21.png'),
  thirtyDays: require('images/30.png'),
  //  badge1: require('images/badge1.png'),
  //  btn_next_day: require('images/btn_next_day.png'),
  //  ic_active_plan: require('images/ic_active_plan.png'),
  ic_add_16: require('images/ic_add_16.png'),
  ic_add_all: require('images/ic_add_all.png'),
  ic_add_body_index: require('images/ic_add_body_index.png'),
  ic_add_exercise: require('images/ic_add_exercise.png'),
  ic_add_food: require('images/ic_add_food.png'),
  ic_add_plan: require('images/ic_add_plan.png'),
  ic_add_water: require('images/ic_add_water.png'),
  ic_arr_right: require('images/ic_arr_right.png'),
  //  ic_barcode_scan_24: require('images/ic_barcode_scan_24.png'),
  //  ic_blank: require('images/ic_blank.png'),
  //  ic_breakfast: require('images/ic_breakfast.png'),
  //  ic_calendar: require('images/ic_calendar.png'),
  //  ic_calories_burn: require('images/ic_calories_burn.png'),
  //  ic_serving: require('images/ic_serving.png'),
  //  ic_nutrition_info: require('images/ic_nutrition_info.png'),
  //  ic_close_24: require('images/ic_close_24.png'),
  //  ic_delete_day: require('images/ic_delete_day.png'),
  //  ic_delete_wo_plan: require('images/ic_delete_wo_plan.png'),
  // ic_diary_active: require('images/ic_diary_active.png'),
  // ic_diary_normal: require('images/ic_diary_normal.png'),
  challenges_active: require('images/challenges_active.png'),
  challenges_inactive: require('images/challenges_inactive.png'),
  activity_active: require('images/activity_active.png'),
  activity_inactive: require('images/activity_inactive.png'),
  teams_active: require('images/teams_active.png'),
  teams_inactive: require('images/teams_inactive.png'),
  achievements_active: require('images/achievements_active.png'),
  achievements_inactive: require('images/achievements_inactive.png'),
  star_active: require('images/star_active.png'),
  star_inactive: require('images/star_inactive.png'),
  profile_active: require('images/profile_active.png'),
  profile_inactive: require('images/profile_inactive.png'),

  //  ic_dinner: require('images/ic_dinner.png'),
   BG1: require('images/BG_1.png'),
   BG2: require('images/BG_2.png'),
   BG3: require('images/BG_3.png'),
   BG4: require('images/BG_4.png'),
   BG5: require('images/BG_5.png'),
  //  logoIntro: require('images/logoIntro.png'),
  //  ic_facebook: require('images/ic_facebook.png'),
  //  ic_email_16: require('images/ic_email_16.png'),
  //  logoSignUp: require('images/logoSignUp.png'),
  or: require('images/or.png'),
   ic_back: require('images/ic_back.png'),
  //  img_user_photo: require('images/img_user_photo.png'),
  //  img_build_muscle: require('images/img_build_muscle.png'),
  //  ic_exercire_normal: require('images/ic_exercire_normal.png'),
  //  ic_exercire_active: require('images/ic_exercire_active.png'),
  //  ic_workout_normal: require('images/ic_workout_normal.png'),
  //  ic_workout_active: require('images/ic_workout_active.png'),
  //  ic_more_active: require('images/ic_more_active.png'),
  //  ic_more_normal: require('images/ic_more_normal.png'),
  //  bg_tab: require('images/bg_tab.png'),
   ic_notification: require('images/ic_notification.png'),
  //  avatar: require('images/avatar.png'),
  //  graph: require('images/graph.png'),
  //  ic_time_16: require('images/ic_time_16.png'),
  //  ic_food_checked: require('images/ic_food_checked.png'),
  //  ic_glass_full: require('images/ic_glass_full.png'),
  ic_glass_plus: require('images/ic_glass_plus.png'),
  //  ic_glass_empty: require('images/ic_glass_empty.png'),
   ic_upgrade_pro: require('images/ic_upgrade_pro.png'),
  //  ic_my_profile: require('images/ic_my_profile.png'),
  //  ic_my_food: require('images/ic_my_food.png'),
  //  ic_graph: require('images/ic_graph.png'),
  //  ic_watch: require('images/ic_watch.png'),
  //  ic_blog: require('images/ic_blog.png'),
  //  ic_help: require('images/ic_help.png'),
  //  ic_settings: require('images/ic_settings.png'),
  ic_search_16: require('images/ic_search_16.png'),
  ic_search: require('images/ic_search.png'),
  //  ic_exercise_list: require('images/ic_exercise_list.png'),
  //  ic_user_exercises: require('images/ic_user_exercises.png'),
  //  ic_user_plan: require('images/ic_user_plan.png'),
  //  ic_close_search: require('images/ic_close_search.png'),
  //  ic_checkbox_selected: require('images/ic_checkbox_selected.png'),
  //  ic_checkbox: require('images/ic_checkbox.png'),
  //  ic_rating_16: require('images/ic_rating_16.png'),
  //  img_logo_google: require('images/img_logo_google.png'),
  //  img_logo_healthkit: require('images/img_logo_healthkit.png'),
  //  img_logo_runkeeper: require('images/img_logo_runkeeper.png'),
  //  img_logo_connect: require('images/img_logo_connect.png'),
  //  img_logo_fitbit: require('images/img_logo_fitbit.png'),
  //  ic_connected: require('images/ic_connected.png'),
  //  img_mg_chest: require('images/img_mg_chest.png'),
  //  img_mg_biceps: require('images/img_mg_biceps.png'),
  //  img_mg_triceps: require('images/img_mg_triceps.png'),
  //  img_exercise_detail: require('images/img_exercise_detail.png'),
  //  ic_play: require('images/ic_play.png'),
  //  img_intruction: require('images/img_intruction.png'),
  //  point: require('images/point.png'),
  //  ic_x: require('images/ic_x.png'),
  //  ic_edit: require('images/ic_edit.png'),
  //  GeneralTraining: require('images/GeneralTraining.png'),
  //  GeneralTraining2: require('images/GeneralTraining2.png'),
  //  GeneralTraining3: require('images/GeneralTraining3.png'),
  //  myplan1: require('images/myplan1.png'),
  //  myplan2: require('images/myplan2.png'),
  //  myplan3: require('images/myplan3.png'),
  //  ic_level: require('images/ic_level.png'),
  //  ic_time_16_w: require('images/ic_time_16_w.png'),
  //  ic_share: require('images/ic_share.png'),
  //  ic_option: require('images/ic_option.png'),
  //  fr1: require('images/fr1.png'),
  //  fr2: require('images/fr2.png'),
  //  fr3: require('images/fr3.png'),
  //  fr4: require('images/fr4.png'),
  //  fr5: require('images/fr5.png'),
  //  fr6: require('images/fr6.png'),
  //  fr7: require('images/fr7.png'),
  //  ic_create_food: require('images/ic_create_food.png'),
  //  ic_barcode_scan: require('images/ic_barcode_scan.png'),
  //  ic_food_category: require('images/ic_food_category.png'),
  //  ic_simple_calories: require('images/ic_simple_calories.png'),
  //  ic_frequent_food: require('images/ic_frequent_food.png'),
  //  ic_recent_food: require('images/ic_recent_food.png'),
  //  ic_list: require('images/ic_list.png'),
  //  beer: require('images/beer.png'),
  //  bread: require('images/bread.png'),
  //  eggs: require('images/eggs.png'),
  //  drinks: require('images/drinks.png'),
  //  fish: require('images/fish.png'),
  //  cupboard: require('images/cupboard.png'),
  //  cereals: require('images/cereals.png'),
  //  seafood: require('images/seafood.png'),
  //  bread1: require('images/bread1.png'),
  //  bread2: require('images/bread2.png'),
  //  bread3: require('images/bread3.png'),
  //  bread4: require('images/bread4.png'),
  //  bread5: require('images/bread5.png'),
  //  bread6: require('images/bread6.png'),
  //  bread7: require('images/bread7.png'),
  //  bread8: require('images/bread8.png'),
  ic_arr_right2: require('images/ic_arr_right2.png'),
  //  ic_camera: require('images/ic_camera.png'),
  //  food_detail: require('images/food_detail.png'),
  //  ic_snack: require('images/ic_snack.png'),
  //  ic_lunch: require('images/ic_lunch.png'),
  //  selected_mask: require('images/selected_mask.png'),
  //  img_recipe: require('images/img_recipe.png'),
  //  img_latest: require('images/img_latest.png'),
  //  img_latest1: require('images/img_latest1.png'),
  //  img_latest2: require('images/img_latest2.png'),
  //  img_latest3: require('images/img_latest3.png'),
  //  img_latest4: require('images/img_latest4.png'),
  //  img_nu1: require('images/img_nu1.png'),
  //  img_nu2: require('images/img_nu2.png'),
  //  img_nu3: require('images/img_nu3.png'),
  //  img_nu4: require('images/img_nu4.png'),
  //  img_nu: require('images/img_nu.png'),
  //  ic_bookmark_normal: require('images/ic_bookmark_normal.png'),
  //  img_avatar: require('images/img_avatar.png'),
  ic_upgrade_pro_1: require('images/ic_upgrade_pro_1.png'),
  ic_edit_profile: require('images/ic_edit_profile.png'),
  //  ic_change_goal: require('images/ic_change_goal.png'),
  //  ic_my_photo: require('images/ic_my_photo.png'),
  //  ic_blog_bookmark: require('images/ic_blog_bookmark.png'),
  ic_invite_friend: require('images/ic_invite_friend.png'),
  //  img_1: require('images/img_1.png'),
  //  img_2: require('images/img_2.png'),
  //  img_3: require('images/img_3.png'),
  //  img_4: require('images/img_4.png'),
  //  img_5: require('images/img_5.png'),
  //  img_6: require('images/img_6.png'),
  //  img_7: require('images/img_7.png'),
  //  img_8: require('images/img_8.png'),
  //  img_9: require('images/img_9.png'),
  //  img_10: require('images/img_10.png'),
  //  img_11: require('images/img_11.png'),
  //  img_12: require('images/img_12.png'),
  //  img_13: require('images/img_13.png'),
  //  noti1: require('images/noti1.png'),
  //  noti2: require('images/noti2.png'),
  //  noti3: require('images/noti3.png'),
  //  noti4: require('images/noti4.png'),
  //  noti5: require('images/noti5.png'),
  //  noti6: require('images/noti6.png'),
  //  video: require('images/video.mp4'),
   ic_capture: require('images/ic_capture.png'),
   bg_take_photo: require('images/bg_take_photo.png'),
   img_star: require('images/star.png'),
   arr_up: require('images/arr_up.png'),
   badge: require('images/badge.png'),
   badgedefault: require('images/badgedefault.png'),
   whitebadge: require('images/whitebadge.png'),
   badge0: require('images/badgelevel0.png'),
   badge1: require('images/badgelevel1.png'),
   badge2: require('images/badgelevel2.png'),
   badge3: require('images/badgelevel3.png'),
   smashIcon: require('images/icon.png'),
});
